#ifndef GRAPHSAGE_CONSTANTS_HPP
#define GRAPHSAGE_CONSTANTS_HPP

#define GRAPHSAGE_VERTEX_COUNT 6
#define GRAPHSAGE_EDGE_COUNT 12
#define GRAPHSAGE_FEATURE_DIMENSION 3
#define GRAPHSAGE_OUTPUT_COUNT (GRAPHSAGE_VERTEX_COUNT * GRAPHSAGE_FEATURE_DIMENSION)

#endif
