/*
 *
 *                   _/_/_/    _/_/   _/    _/ _/_/_/    _/_/
 *                  _/   _/ _/    _/ _/_/  _/ _/   _/ _/    _/
 *                 _/_/_/  _/_/_/_/ _/  _/_/ _/   _/ _/_/_/_/
 *                _/      _/    _/ _/    _/ _/   _/ _/    _/
 *               _/      _/    _/ _/    _/ _/_/_/  _/    _/
 *
 *             ***********************************************
 *                              PandA Project
 *                     URL: http://panda.dei.polimi.it
 *                       Politecnico di Milano - DEIB
 *                        System Architectures Group
 *             ***********************************************
 *              Copyright (C) 2022-2026 Politecnico di Milano
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 *
 *   This file is part of the PandA framework.
 *
 *   Licensed under the Apache License, Version 2.0, with BAMBU exceptions (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 */
/**
 * @file PrintfNHDLGenerator.cpp
 * @brief Implementation of the HDL generator for the variadic printf helper module.
 *
 * @author Michele Fiorito <michele.fiorito@polimi.it>
 * @author Fabrizio Ferrandi <fabrizio.ferrandi@polimi.it>
 *
 */

#include "PrintfNHDLGenerator.hpp"

#include "BambuParameter.hpp"
#include "hls_manager.hpp"
#include "language_writer.hpp"
#include "memory.hpp"
#include "memory_allocation.hpp"

PrintfNHDLGenerator::PrintfNHDLGenerator(const HLS_managerRef& _HLSMgr) : Registrar(_HLSMgr)
{
}

void PrintfNHDLGenerator::InternalExec(std::ostream& out, structural_objectRef /* mod */,
                                       unsigned int /* function_id */, gc_vertex_descriptor /* op_v */,
                                       const HDLWriter_Language /* language */,
                                       const std::vector<HDLGenerator::parameter>& _p,
                                       const std::vector<HDLGenerator::parameter>& /* _ports_in */,
                                       const std::vector<HDLGenerator::parameter>& /* _ports_out */,
                                       const std::vector<HDLGenerator::parameter>& /* _ports_inout */)
{
   const auto selector_dimension = STR(_p.size() < 2U ? 2U : _p.size());
   const auto selector_left = STR(((_p.size() - 1U) < 1U) ? 1U : (_p.size() - 1U));

   const auto Param = HLSMgr->get_parameter();
   const auto emulate_bram =
       Param->getOption<MemoryAllocation_Policy>(OPT_memory_allocation_policy) == MemoryAllocation_Policy::ALL_BRAM ||
       Param->getOption<MemoryAllocation_Policy>(OPT_memory_allocation_policy) ==
           MemoryAllocation_Policy::EXT_PIPELINED_BRAM;
   const auto use_datardy =
       STR((emulate_bram ? "             if(Mout_oe_ram_reg)\n" : "             if(M_DataRdy0[0])\n"));
   const auto emulate_bram_str = STR("reg Mout_oe_ram_reg;\n"
                                     "always @ (posedge clock 1RESET_EDGE)\n"
                                     "  if (1RESET_VALUE)\n"
                                     "  begin\n"
                                     "    Mout_oe_ram_reg <= 0;\n"
                                     "  end else begin\n"
                                     "    Mout_oe_ram_reg <= active_request;\n"
                                     "  end\n");

   std::string case_statement;
   if(_p.size() > 1)
   {
      case_statement = "case (_present_selector)\n";
      for(auto i = 0U, selector = 1U; i < _p.size(); i++, selector *= 2)
      {
         case_statement += "            " + selector_dimension + "'d" + STR(selector) +
                           ":\n"
                           "             begin\n"
                           "               data1=" +
                           _p[i].name +
                           ";\n"
                           "               data1_size=BITSIZE_in" +
                           STR(i + 1) +
                           ";\n"
                           "             end\n";
      }
      case_statement += "            default:\n"
                        "             begin\n"
                        "               data1 = 64'b0;\n"
                        "               data1_size = 8'b0;\n"
                        "             end\n"
                        "          endcase";
   }
   else
   {
      case_statement = "";
   }
   const auto fsm =
       ""
       "// synthesis translate_off\n"
       "function real bits32_to_real64;\n"
       "  input [31:0] fin1;\n"
       "  reg [7:0] exponent1;\n"
       "  reg is_exp_zero;\n"
       "  reg is_all_ones;\n"
       "  reg [10:0] exp_tmp;\n"
       "  reg [63:0] fout1;\n"
       "begin\n"
       "  exponent1 = fin1[30:23];\n"
       "  is_exp_zero = exponent1 == 8'd0;\n"
       "  is_all_ones = exponent1 == {8{1'b1}};\n"
       "  exp_tmp = {3'd0, exponent1} + 11'd896;\n"
       "  fout1[63] = fin1[31];\n"
       "  fout1[62:52] = is_exp_zero ? 11'd0 : (is_all_ones ? {11{1'b1}} : exp_tmp);\n"
       "  fout1[51:29] = fin1[22:0];\n"
       "  fout1[28:0] = 29'd0;\n"
       "  bits32_to_real64 = $bitstoreal(fout1);\n"
       "end\n"
       "endfunction\n"
       "// synthesis translate_on\n"
       "reg [BITSIZE_Mout_addr_ram-1:0] _present_pointer;\n"
       "reg [BITSIZE_Mout_addr_ram-1:0] _next_pointer;\n"
       "reg [BITSIZE_Mout_addr_ram-1:0] _present_pointer1;\n"
       "reg [BITSIZE_Mout_addr_ram-1:0] _next_pointer1;\n"
       "reg done_port;\n"
       "reg [(PORTSIZE_Mout_addr_ram*BITSIZE_Mout_addr_ram)+(-1):0] Mout_addr_ram;\n"
       "reg [(PORTSIZE_Mout_Wdata_ram*BITSIZE_Mout_Wdata_ram)+(-1):0] Mout_Wdata_ram;\n"
       "reg [(PORTSIZE_Mout_data_ram_size*BITSIZE_Mout_data_ram_size)+(-1):0] Mout_data_ram_size;\n"
       "reg [PORTSIZE_Mout_oe_ram-1:0] Mout_oe_ram0;\n"
       "reg [PORTSIZE_Mout_we_ram-1:0] Mout_we_ram0;\n"
       "wire [PORTSIZE_M_DataRdy-1:0] M_DataRdy0;\n"
       "reg active_request;\n"
       "reg active_request_next;\n" +
       (emulate_bram ? emulate_bram_str : "") +
       "\n"
       "parameter [2:0] S_0 = 3'd0,\n"
       "  S_1 = 3'd1,\n"
       "  S_2 = 3'd2,\n"
       "  S_3 = 3'd3,\n"
       "  S_4 = 3'd4,\n"
       "  S_5 = 3'd5,\n"
       "  S_6 = 3'd6,\n"
       "  S_7 = 3'd7;\n"
       "reg [2:0] present_state;\n"
       "reg [2:0] next_state;\n"
       "reg [" +
       selector_left +
       ":0] _present_selector;\n"
       "reg [" +
       selector_left +
       ":0] _next_selector;\n"
       "reg [63:0] data1;\n"
       "reg [7:0] _present_data2;\n"
       "reg [7:0] _next_data2;\n"
       "reg [7:0] data1_size;\n"
       "reg write_done;\n"
       "\n"
       "  always @(posedge clock 1RESET_EDGE)\n"
       "    if (1RESET_VALUE)\n"
       "      begin\n"
       "        present_state <= S_0;\n"
       "        _present_pointer <= {BITSIZE_Mout_addr_ram{1'b0}};\n"
       "        _present_pointer1 <= {BITSIZE_Mout_addr_ram{1'b0}};\n"
       "        _present_selector <=" +
       selector_dimension +
       "'d0;\n"
       "        _present_data2 <= 8'b0;\n"
       "      end\n"
       "    else\n"
       "      begin\n"
       "        present_state <= next_state;\n"
       "        _present_pointer <= _next_pointer;\n"
       "        _present_pointer1 <= _next_pointer1;\n"
       "        _present_selector <= _next_selector;\n"
       "        _present_data2 <= _next_data2;\n"
       "      end\n"
       "\n"
       "  always @(posedge clock 1RESET_EDGE)\n"
       "  begin\n"
       "    if (1RESET_VALUE)\n"
       "    begin\n"
       "      active_request <= 0;\n"
       "    end\n"
       "    else\n"
       "    begin\n"
       "      active_request <= active_request_next;\n"
       "    end\n"
       "  end\n"
       "  assign M_DataRdy0 = M_DataRdy;\n"
       "  assign Mout_oe_ram = Mout_oe_ram0;\n"
       "  assign Mout_we_ram = Mout_we_ram0;\n"
       "  always @(*)\n"
       "      begin\n"
       "        Mout_we_ram0 = Min_we_ram;\n"
       "        Mout_Wdata_ram = Min_Wdata_ram;\n"
       "        Mout_oe_ram0=Min_oe_ram;\n"
       "        Mout_addr_ram=Min_addr_ram;\n"
       "        Mout_data_ram_size=Min_data_ram_size;\n"
       "        done_port = 1'b0;\n"
       "        active_request_next =1'b0;\n"
       "        next_state = present_state;\n"
       "        _next_pointer = _present_pointer;\n"
       "        _next_pointer1 = _present_pointer1;\n"
       "        _next_selector = _present_selector;\n"
       "        _next_data2 = _present_data2;\n"
       "        " +
       case_statement +
       "\n"
       "        case (present_state)\n"
       "          S_0:\n"
       "            if(start_port)\n"
       "              begin\n"
       "                _next_pointer=0;\n"
       "                _next_pointer1=0;\n"
       "                next_state=S_1;  \n"
       "                active_request_next =1'b1;\n"
       "                _next_selector=" +
       selector_dimension +
       "'d2;\n"
       "              end\n"
       "            \n"
       "         S_1:\n"
       "           begin\n"
       "             Mout_addr_ram[BITSIZE_Mout_addr_ram-1:0]=(in1[BITSIZE_Mout_addr_ram-1:0]+_present_pointer) & "
       "{BITSIZE_Mout_addr_ram{active_request}};\n"
       "             Mout_data_ram_size[BITSIZE_Mout_data_ram_size-1:0]={{BITSIZE_Mout_data_ram_size-4{1'b0}}, 4'd8} & "
       "{BITSIZE_Mout_data_ram_size{active_request}};\n"
       "             Mout_oe_ram0[0]=active_request;\n" +
       use_datardy +
       "             begin\n"
       "                _next_data2 = M_Rdata_ram[7:0];\n"
       "                next_state=S_2;\n"
       "// synthesis translate_off\n"
       "                write_done=1'b0;\n"
       "// synthesis translate_on\n"
       "             end\n"
       "           end\n"
       "         S_2:\n"
       "           begin\n"
       "             _next_pointer=_present_pointer+1'd1;\n"
       "             if((_present_data2!=8'd0)&&(_present_data2!=8'd37))\n"
       "             begin\n"
       "// synthesis translate_off\n"
       "               if(!write_done)\n"
       "               begin\n"
       "                 $write(\"%c\",_present_data2);\n"
       "                 write_done=1'b1;\n"
       "               end\n"
       "// synthesis translate_on\n"
       "               next_state=S_1;\n"
       "               active_request_next =1'b1;\n"
       "             end\n"
       "             else if(_present_data2==8'd37)\n"
       "             begin\n"
       "               next_state=S_3;\n"
       "               active_request_next =1'b1;\n"
       "             end\n"
       "             else if(_present_data2==8'd0)\n"
       "             begin\n"
       "               done_port = 1'b1;\n"
       "               next_state=S_0;\n"
       "             end\n"
       "           end\n"
       "         S_3:\n"
       "           begin\n"
       "             Mout_addr_ram[BITSIZE_Mout_addr_ram-1:0]=(in1[BITSIZE_Mout_addr_ram-1:0]+_present_pointer) & "
       "{BITSIZE_Mout_addr_ram{active_request}};\n"
       "             Mout_data_ram_size[BITSIZE_Mout_data_ram_size-1:0]={{BITSIZE_Mout_data_ram_size-4{1'b0}}, 4'd8} & "
       "{BITSIZE_Mout_data_ram_size{active_request}};\n"
       "             Mout_oe_ram0[0]=active_request;\n" +
       use_datardy +
       "             begin\n"
       "                _next_data2 = M_Rdata_ram[7:0];\n"
       "                next_state=S_5;\n"
       "// synthesis translate_off\n"
       "                write_done=1'b0;\n"
       "// synthesis translate_on\n"
       "             end\n"
       "           end\n"
       "         S_5 :\n"
       "           begin\n"
       "             next_state=S_6;\n"
       "             _next_pointer=_present_pointer+1'd1;\n"
       "             case(_present_data2)\n"
       "               8'd37: //%%\n"
       "               begin\n"
       "                 next_state=S_1;\n"
       "                 active_request_next =1'b1;\n"
       "// synthesis translate_off\n"
       "                 if(!write_done)\n"
       "                 begin\n"
       "                   $write(\"%c\",8'd37);\n"
       "                   write_done=1'b1;\n"
       "                 end\n"
       "// synthesis translate_on\n"
       "               end\n"
       "               8'd99: //Char\n"
       "               begin\n"
       "// synthesis translate_off\n"
       "                 if(!write_done)\n"
       "                 begin\n"
       "                   $write(\"%c\",data1[7:0]);\n"
       "                   write_done=1'b1;\n"
       "                 end\n"
       "// synthesis translate_on\n"
       "               end\n"
       "               8'd100: //Decimal %d\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd16)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1[15:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd8)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1[7:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Decimal precision not supported (d) %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               8'd105: //Decimal %i\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd16)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1[15:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd8)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$signed(data1[7:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Decimal precision not supported (i) %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               8'd101: //Exponential %e\n"
       "               begin\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%e\",$bitstoreal(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%e\",bits32_to_real64(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Floating point precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               end\n"
       "               8'd69: //Exponential %E\n"
       "               begin\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%e\",$bitstoreal(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%e\",bits32_to_real64(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Floating point precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               end\n"
       "               8'd102: //Float %f\n"
       "               begin\n"
       "                 if(data1_size==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20f\",$bitstoreal(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20f\",bits32_to_real64(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Floating point precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               end\n"
       "               8'd70: //Float %F\n"
       "               begin\n"
       "                 if(data1_size==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20f\",$bitstoreal(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20f\",bits32_to_real64(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Floating point precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               end\n"
       "               8'd103: //Float %g\n"
       "               begin\n"
       "                 if(data1_size==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20g\",$bitstoreal(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20g\",bits32_to_real64(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Floating point precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               end\n"
       "               8'd71: //Float %G\n"
       "               begin\n"
       "                 if(data1_size==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20g\",$bitstoreal(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%20.20g\",bits32_to_real64(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Floating point precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               end\n"
       "               8'd111: //Octal\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0o\",data1);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0o\",data1[31:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd16)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0o\",data1[15:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd8)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0o\",data1[7:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Octal precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               8'd112: //%p\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                 if(!write_done)\n"
       "                 begin\n"
       "                   $write(\"0x%0h\",data1);\n"
       "                   write_done=1'b1;\n"
       "                 end\n"
       "// synthesis translate_on\n"
       "               end\n"
       "               8'd115: //String\n"
       "               begin\n"
       "                 next_state=S_7;\n"
       "                 active_request_next =1'b1;\n"
       "                 _next_pointer1=0;\n"
       "               end\n"
       "               8'd117: //unsigned int %u TO BE FIXED\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$unsigned(data1));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$unsigned(data1[31:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd16)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$unsigned(data1[15:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd8)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0d\",$unsigned(data1[7:0]));\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Unsigned precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               8'd120: //Hex %x\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1[31:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd16)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1[15:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd8)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1[7:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Hex precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               8'd88: //Hex %X\n"
       "                 if(data1_size ==8'd64)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd32)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1[31:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd16)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1[15:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else if(data1_size ==8'd8)\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   if(!write_done)\n"
       "                   begin\n"
       "                     $write(\"%0h\",data1[7:0]);\n"
       "                     write_done=1'b1;\n"
       "                   end\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "                 else\n"
       "                 begin\n"
       "// synthesis translate_off\n"
       "                   $display(\"ERROR - Hex precision not supported %d\", data1_size);\n"
       "                   $finish;\n"
       "// synthesis translate_on\n"
       "                 end\n"
       "               default:\n"
       "               begin\n"
       "                 next_state=S_3;\n"
       "                 active_request_next =1'b1;\n"
       "               end\n"
       "             endcase\n"
       "           end\n"
       "         S_6:\n"
       "           begin\n"
       "             _next_selector=_present_selector<<1;\n"
       "             next_state=S_1;\n"
       "             active_request_next =1'b1;\n"
       "           end\n"
       "         S_7:\n"
       "           begin\n"
       "             Mout_addr_ram[BITSIZE_Mout_addr_ram-1:0]=(data1[BITSIZE_Mout_addr_ram-1:0]+_present_pointer1) & "
       "{BITSIZE_Mout_addr_ram{active_request}};\n"
       "             Mout_data_ram_size[BITSIZE_Mout_data_ram_size-1:0]={{BITSIZE_Mout_data_ram_size-4{1'b0}}, 4'd8} & "
       "{BITSIZE_Mout_data_ram_size{active_request}};\n"
       "             Mout_oe_ram0[0]=active_request;\n" +
       use_datardy +
       "             begin\n"
       "               _next_data2 = M_Rdata_ram[7:0];\n"
       "               next_state=S_4;\n"
       "// synthesis translate_off\n"
       "               write_done=1'b0;\n"
       "// synthesis translate_on\n"
       "             end\n"
       "           end\n"
       "         S_4:\n"
       "           begin\n"
       "             _next_pointer1=_present_pointer1+1'd1;\n"
       "             if(_present_data2!=8'd0)\n"
       "             begin\n"
       "// synthesis translate_off\n"
       "               if(!write_done)\n"
       "               begin\n"
       "                 $write(\"%c\",_present_data2);\n"
       "                 write_done=1'b1;\n"
       "               end\n"
       "// synthesis translate_on\n"
       "               next_state=S_7;\n"
       "               active_request_next =1'b1;\n"
       "             end\n"
       "             else\n"
       "               next_state=S_6;\n"
       "           end\n"
       "      endcase\n"
       "  end\n";

   out << fsm;
}
