/*
 *
 *                   _/_/_/    _/_/   _/    _/ _/_/_/    _/_/
 *                  _/   _/ _/    _/ _/_/  _/ _/   _/ _/    _/
 *                 _/_/_/  _/_/_/_/ _/  _/_/ _/   _/ _/_/_/_/
 *                _/      _/    _/ _/    _/ _/   _/ _/    _/
 *               _/      _/    _/ _/    _/ _/_/_/  _/    _/
 *
 *             ***********************************************
 *                              PandA Project
 *                     URL: http://panda.dei.polimi.it
 *                       Politecnico di Milano - DEIB
 *                        System Architectures Group
 *             ***********************************************
 *              Copyright (C) 2025-2026 Politecnico di Milano
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 *
 *   This file is part of the PandA framework.
 *
 *   Licensed under the Apache License, Version 2.0, with BAMBU exceptions (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 */
/**
 * JSON parser of the trace event list generated by the simulation
 * @author Fabrizio Ferrandi <fabrizio.ferrandi@polimi.it>
 */
#include "JSON_parse_discrepancy.hpp"

#include "Discrepancy.hpp"
#include "UnfoldedCallGraph.hpp"
#include "exceptions.hpp"
#include "fileIO.hpp"
#include "string_manipulation.hpp"

#include <glaze/glaze.hpp>

#include <cstdint>
#include <iostream>
#include <iterator>
#include <optional>
#include <stack>
#include <string>
#include <utility>
#include <vector>

namespace
{
   struct JsonAddrEntry
   {
      unsigned int var_id{};
      uint64_t addr{};
   };

   struct JsonEvent
   {
      std::string type;
      std::optional<unsigned int> call_id;
      std::optional<uint64_t> context;
      std::optional<unsigned int> called_id;
      std::vector<JsonAddrEntry> addr_table;
      std::optional<unsigned int> bb;
      std::optional<unsigned int> op_id;
      std::optional<std::string> value;
   };

   struct JsonTrace
   {
      std::vector<JsonEvent> events;
   };
} // namespace

template <>
struct glz::meta<JsonAddrEntry>
{
   using T = JsonAddrEntry;
   static constexpr auto value = glz::object(&T::var_id, &T::addr);
};

template <>
struct glz::meta<JsonEvent>
{
   using T = JsonEvent;
   static constexpr auto value =
       glz::object(&T::type, &T::call_id, &T::context, &T::called_id, &T::addr_table, &T::bb, &T::op_id, &T::value);
};

template <>
struct glz::meta<JsonTrace>
{
   using T = JsonTrace;
   static constexpr auto value = glz::object(&T::events);
};

void JSON_parse_discrepancy(const std::string& c_trace_filename, DiscrepancyRef Discrepancy)
{
   try
   {
      const auto input_file = fileIO_istream_open(c_trace_filename);
      if(input_file->fail())
      {
         THROW_ERROR(std::string("Failed opening discrepancy data file: ") + c_trace_filename);
      }

      const std::string json_data((std::istreambuf_iterator<char>(*input_file)), std::istreambuf_iterator<char>());
      const auto parsed = glz::read_json<JsonTrace>(json_data);
      if(!parsed)
      {
         THROW_ERROR("Error parsing discrepancy JSON data: " + glz::format_error(parsed.error(), json_data));
      }

      const auto& trace = parsed.value();
      std::stack<uint64_t> context_stack;
      std::stack<UnfoldedCallGraph::vertex_descriptor> vertex_stack;

      for(const auto& event : trace.events)
      {
         if(event.type == "initial_context")
         {
            THROW_ASSERT(event.context.has_value(), "initial_context missing context id");
            const uint64_t context = event.context.value();
            THROW_ASSERT(context_stack.empty(), "initial_context = " + STR(context));
            Discrepancy->c_addr_map[context];
            context_stack.push(context);
            THROW_ASSERT(vertex_stack.empty(), "initial_context = " + STR(context));
            for(const auto& entry : event.addr_table)
            {
               Discrepancy->c_addr_map[context][entry.var_id] = entry.addr;
            }
         }
         else if(event.type == "context")
         {
            THROW_ASSERT(event.context.has_value(), "context event missing context id");
            THROW_ASSERT(event.call_id.has_value(), "context event missing call id");
            THROW_ASSERT(event.called_id.has_value(), "context event missing called id");
            const uint64_t new_context = event.context.value();
            const unsigned int call_id = event.call_id.value();
            const unsigned int called_id = event.called_id.value();
            THROW_ASSERT(!context_stack.empty(), "context = " + STR(new_context));

            Discrepancy->c_addr_map[new_context];
            THROW_ASSERT(Discrepancy->c_addr_map.find(context_stack.top()) != Discrepancy->c_addr_map.end(),
                         "cant find address map for context " + STR(context_stack.top()));
            for(const auto& addr_pair : Discrepancy->c_addr_map.at(context_stack.top()))
            {
               Discrepancy->c_addr_map[new_context].insert(addr_pair);
            }
            context_stack.push(new_context);

            if(vertex_stack.empty())
            {
               vertex_stack.push(Discrepancy->unfolded_root_v);
            }
            else
            {
               auto& ufcg = Discrepancy->DiscrepancyCallGraph;
#if HAVE_ASSERTS
               bool found = false;
#endif
               for(const auto& oe : ufcg.out_edges(vertex_stack.top()))
               {
                  if(ufcg.CGetEdgeInfo(oe).call_id == call_id)
                  {
                     auto tgt = ufcg.target(oe);
                     if(ufcg.CGetNodeInfo(tgt).f_id == called_id)
                     {
                        vertex_stack.push(tgt);
#if HAVE_ASSERTS
                        found = true;
#endif
                        break;
                     }
                  }
               }
               THROW_ASSERT(found, "new target vertex not found");
            }

            THROW_ASSERT(Discrepancy->unfolded_v_to_scope.find(vertex_stack.top()) !=
                             Discrepancy->unfolded_v_to_scope.end(),
                         std::string("can't find scope for new vertex ") +
                             STR(Discrepancy->DiscrepancyCallGraph.CGetNodeInfo(vertex_stack.top()).f_id));
            Discrepancy->context_to_scope[new_context] = Discrepancy->unfolded_v_to_scope.at(vertex_stack.top());

            for(const auto& entry : event.addr_table)
            {
               Discrepancy->c_addr_map[context_stack.top()][entry.var_id] = entry.addr;
            }
         }
         else if(event.type == "context_end")
         {
            if(context_stack.empty())
            {
               THROW_ERROR("malformed call stack trace");
            }
            const auto context_depth = context_stack.size();
            const auto vertex_depth = vertex_stack.size();
            if(context_depth != vertex_depth + 1)
            {
               THROW_ERROR("malformed call stack trace");
            }
            context_stack.pop();
            if(!vertex_stack.empty())
            {
               vertex_stack.pop();
            }
         }
         else if(event.type == "control_flow")
         {
            THROW_ASSERT(event.bb.has_value(), "control_flow event missing bb id");
            THROW_ASSERT(!vertex_stack.empty(), "control_flow event missing function context");
            if(context_stack.empty())
            {
               THROW_ERROR("malformed call stack trace");
            }
            const auto fsm_fun_id = Discrepancy->DiscrepancyCallGraph.CGetNodeInfo(vertex_stack.top()).f_id;
            Discrepancy->c_control_flow_trace[fsm_fun_id][context_stack.top()].emplace_back(event.bb.value());
         }
         else if(event.type == "op_trace")
         {
            THROW_ASSERT(event.op_id.has_value(), "op_trace event missing op id");
            THROW_ASSERT(event.value.has_value(), "op_trace event missing value");
            if(context_stack.empty())
            {
               THROW_ERROR("malformed call stack trace");
            }

            const auto op_id = event.op_id.value();
            Discrepancy->c_op_trace[op_id].emplace_back(context_stack.top(), event.value.value());
         }
         else
         {
            THROW_ERROR("Unknown discrepancy event type: " + event.type);
         }
      }
      return;
   }
   catch(const char* msg)
   {
      std::cerr << msg << std::endl;
   }
   catch(const std::string& msg)
   {
      std::cerr << msg << std::endl;
   }
   catch(...)
   {
      std::cerr << "unknown exception" << std::endl;
   }
   THROW_ERROR("Error in parsing trace event file: " + c_trace_filename);
}
