# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.customize [ 'modifyvm', :id, '--vram', '64']
     vb.customize "pre-boot", ["storageattach", :id, "--storagectl", "IDE", "--port", "1", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
     vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
     vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
     vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
     vb.name = "PandA-bambu-VM_64bit"
  end
  #   apt-get install lubuntu-desktop -y
  config.vm.provision "shell", inline: <<-SHELL
     sed -i '1ideb mirror:\/\/mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse' /etc/apt/sources.list
     sed -i '1ideb mirror:\/\/mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse' /etc/apt/sources.list
     sed -i '1ideb mirror:\/\/mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse' /etc/apt/sources.list
     sed -i '1ideb mirror:\/\/mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse' /etc/apt/sources.list
     apt-get update -y
     apt-get upgrade -y
     apt-get install -y linux-headers-$(uname -r) build-essential dkms
     apt-get install -y virtualbox-guest-x11
     apt-get install -y autoconf autoconf-archive automake libtool gcc-7 g++-7 gcc-7-plugin-dev gcc-7-multilib g++-7-multilib gfortran-7 gfortran-7-multilib libboost-all-dev libmpc-dev libmpfr-dev libxml2-dev liblzma-dev libmpfi-dev zlib1g-dev libicu-dev bison doxygen flex graphviz xdot verilator make libsuitesparse-dev libglpk-dev clang-6.0 libclang-6.0-dev libbdd-dev
     apt-get autoremove -y
     git clone https://github.com/ferrandi/PandA-bambu.git
     cd PandA-bambu
     make -f Makefile.init
     mkdir build
     cd build && ../configure --prefix=/home/ubuntu/panda --enable-verilator --enable-glpk --enable-flopoco  --disable-release --enable-experimental --enable-opt --with-opt-level=2 && make && make install
     cd ../.. && chown -R ubuntu:ubuntu PandA-bambu
     mv PandA-bambu /home/ubuntu/
     cd /home/ubuntu/panda/share/panda/examples/arf && chmod +x bambu.sh && ./bambu.sh && rm -rf arf_hls arf_testbench && echo "Bambu is correctly working!!"
     cd /home/ubuntu/
     chown -R ubuntu:ubuntu panda
     apt-get -y install ubuntu-gnome-desktop
     apt-get clean -y
     echo "export PATH=/home/ubuntu/panda/bin:$PATH" >> /home/ubuntu/.bashrc
     echo "ubuntu:password" | chpasswd
     dd if=/dev/zero of=/EMPTY bs=1M
     rm -f /EMPTY
  SHELL
end
