/*! \file */
/*
 * kmp_runtime.cpp -- KPTS runtime support library
 */

//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
/////////////////////////////////////////////////////////////////////////////////////////////
//    bambu customized OpenMP runtime library
//
//    Author Fabrizio Ferrandi - Politecnico di Milano
//
//    November 6, 2020.
//    The original library has been taken from https://github.com/llvm/llvm-project/tree/master/openmp
//    For the additional notes check the associated README.md.
/////////////////////////////////////////////////////////////////////////////////////////////

#include "kmp.h"

__attribute__((always_inline)) int __kmp_get_global_thread_id_reg()
{
   /// the next function is bambu specific and return a unique thread id according the context in which this function is
   /// called
   return KMP_CS_GET_GTID();
}

/* this sets the requested number of threads for the next parallel region
   encountered by this team. since this should be enclosed in the forkjoin
   critical section it should avoid race conditions with asymmetrical nested
   parallelism */
__attribute__((always_inline)) void __kmp_push_num_threads(ident_t* id, int gtid, int num_threads)
{
   KMP_TH_SET_NPROC(gtid, num_threads);
}

/* ------------------------------------------------------------------------ */
/* internal fast reduction routines */

__attribute__((always_inline)) PACKED_REDUCTION_METHOD_T
__kmp_determine_reduction_method(ident_t* loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size,
                                 void* reduce_data, void (*reduce_func)(void* lhs_data, void* rhs_data),
                                 kmp_critical_name* lck)
{
   // Default reduction method: critical construct ( lck != NULL, like in current
   // PAROPT )
   // If ( reduce_data!=NULL && reduce_func!=NULL ): the tree-reduction method
   // can be selected by RTL
   // If loc->flags contains KMP_IDENT_ATOMIC_REDUCE, the atomic reduce method
   // can be selected by RTL
   // Finally, it's up to OpenMP RTL to make a decision on which method to select
   // among generated by PAROPT.

   PACKED_REDUCTION_METHOD_T retval;

   int team_size;

   retval = critical_reduce_block;

   // another choice of getting a team size (with 1 dynamic deference) is slower
   team_size = __kmp_get_team_num_threads(global_tid);
   if(team_size == 1)
   {
      retval = empty_reduce_block;
   }
   else
   {
   }

   return (retval);
}
