# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "fedora/29-cloud-base"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.customize [ 'modifyvm', :id, '--vram', '64']
     vb.customize "pre-boot", ["storageattach", :id, "--storagectl", "IDE", "--port", "1", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
     vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
     vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
     vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
     vb.name = "PandA-bambu-VM_64bit-fedora29"
  end
  config.vm.provision "shell", inline: <<-SHELL
     adduser fedora29
     echo "fedora29:password" | chpasswd
     dnf -y update
     dnf -y install git
     dnf -y install autoconf autoconf-archive libtool boost-devel mpfr-devel xml2 lzma-devel mpfi-devel zlib-devel bison flex doxygen graphviz iverilog verilator gcc gcc-c++ gcc-plugin-devel.x86_64 gcc-plugin-devel.i686 libxml2-devel glibc glibc-devel glibc.i686 glibc-devel.i686 libgcc.i686 make suitesparse-static libtool-ltdl-devel glpk-devel gawk clang clang-devel llvm llvm-devel
     chmod +x /usr/bin/verilator
     git clone https://github.com/ferrandi/PandA-bambu.git
     cd PandA-bambu
     make -f Makefile.init
     mkdir build
     cd build && ../configure --prefix=/home/fedora29/panda --enable-verilator --enable-glpk --enable-opt --enable-flopoco --with-opt-level=fast && make -j2 && make install && make clean
     cd ../.. && chown -R fedora29:fedora29 PandA-bambu
     mv PandA-bambu /home/fedora29/
     cd /home/fedora29/panda/share/panda/examples/arf && chmod +x bambu.sh && ./bambu.sh && rm -rf arf_hls arf_testbench && echo "Bambu is correctly working!!"
     cd /home/fedora29/ 
     chown -R fedora29:fedora29 /home/fedora29/panda
     dd if=/dev/zero of=/EMPTY bs=1M
     rm -f /EMPTY
  SHELL
end
