default: all

all: configure.ac Makefile.am
	@mkdir -p m4
	@autoreconf --install
	
distclean: clean
	@cd abseil-cpp
	@rm -rf ylwrap aclocal.m4 autom4te.cache config.guess config.h.in config.sub configure depcomp install-sh ltmain.sh m4 missing Makefile.in
	@rm -rf config.h config.log config.status libtool stamp-h1 Makefile
	@echo "- Abseil: cleared configuration files -"

clean:
	@cd abseil-cpp
	@rm -rf libabseil* .deps 
	@echo "- Abseil: cleared object files --------"


