# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.customize [ 'modifyvm', :id, '--vram', '64']
     vb.customize "pre-boot", ["storageattach", :id, "--storagectl", "IDE", "--port", "1", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
     vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
     vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
     vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
     vb.name = "PandA-bambu-VM_64bit-CentOS7"
  end
  # Add the following lines in case you would like to have the graphical interface
  #  yum -y groupinstall "GNOME Desktop"
  #  sudo systemctl set-default graphical.target
  #  sudo systemctl start graphical.target
  config.vm.provision "shell", inline: <<-SHELL
     adduser centos7
     echo "centos7:password" | chpasswd
     yum -y update
     yum -y install epel-release git 
     yum -y install autoconf autoconf-archive automake bison boost-devel flex gcc-c++ gcc-plugin-devel glibc-devel.i686 glpk-devel libgcc.i686 libicu-devel libtool libtool-ltdl-devel libxml2-devel make mpfr-devel suitesparse-static xz-devel zlib-devel verilator
     git clone https://github.com/ferrandi/PandA-bambu.git
     cd PandA-bambu
     make -f Makefile.init
     mkdir build
     cd build && ../configure --prefix=/home/centos7/panda --enable-verilator --enable-glpk --enable-opt --disable-flopoco --with-opt-level=fast && make -j2 && make install && make clean
     cd ../.. && chown -R centos7:centos7 PandA-bambu
     mv PandA-bambu /home/centos7/
     cd /home/centos7/panda/share/panda/examples/arf && chmod +x bambu.sh && ./bambu.sh && rm -rf arf_hls arf_testbench && echo "Bambu is correctly working!!"
     cd /home/centos7/
     chown -R centos7:centos7 panda
     yum -y clean 
     dd if=/dev/zero of=/EMPTY bs=1M
     rm -f /EMPTY
  SHELL
end
