# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
     vb.memory = "4096"
     vb.customize [ 'modifyvm', :id, '--uartmode1', 'disconnected']
     vb.customize [ 'modifyvm', :id, '--vram', '64']
     vb.name = "PandA-bambu-VM_64bit-trusty"
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get upgrade -y
     apt-get install -y linux-headers-$(uname -r) build-essential dkms git
     apt-get install -y virtualbox-guest-x11
     apt-get install -y autoconf autoconf-archive automake libtool g++ gcc-4.6 g++-4.6 gcc-4.6-plugin-dev gcc-4.6-plugin-dev gcc-4.7 g++-4.7 gcc-4.8-plugin-dev gcc-4.7-plugin-dev gcc-4.6-multilib gcc-4.7-multilib gcc-4.8-multilib g++-4.8-multilib gfortran-4.6 gfortran-4.6-multilib gfortran-4.7 gfortran-4.7-multilib gfortran-4.8 gfortran-4.8-multilib libboost-all-dev libmpc-dev libmpfr-dev libxml2-dev liblzma-dev libmpfi-dev zlib1g-dev libicu-dev bison doxygen flex graphviz iverilog verilator libsuitesparse-dev libglpk-dev make
     apt-get autoremove -y
     git clone https://github.com/ferrandi/PandA-bambu.git
     cd PandA-bambu
     make -f Makefile.init
     mkdir build
     cd build && ../configure --prefix=/home/ubuntu/panda --enable-verilator --enable-glpk --enable-opt --enable-flopoco --with-opt-level=fast && make -j2 && make install && make clean
     cd ../.. && chown -R ubuntu.ubuntu PandA-bambu
     mv PandA-bambu /home/ubuntu/
     cd /home/ubuntu/
     chown -R ubuntu.ubuntu panda
     cd /home/ubuntu/panda/share/panda/examples/arf && chmod +x bambu.sh && ./bambu.sh && rm -rf hls testbench && echo "Bambu is correctly working!!"
     apt-get clean -y
     echo "export PATH=/home/ubuntu/panda/bin:$PATH" >> /home/ubuntu/.bashrc
     echo "ubuntu:password" | chpasswd
     dd if=/dev/zero of=/EMPTY bs=1M
     rm -f /EMPTY
  SHELL
end
