# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.customize [ 'modifyvm', :id, '--vram', '64']
     vb.customize "pre-boot", ["storageattach", :id, "--storagectl", "IDE", "--port", "1", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
     vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
     vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
     vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
     vb.name = "PandA-bambu-VM_64bit-ArchLinux"
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo useradd -m archlinux
     echo "archlinux:password" | chpasswd
     sudo pacman -Syu --noconfirm
     sudo pacman -S base-devel multilib-devel boost iverilog gcc-multilib autoconf-archive verilator mpfi clang llvm gcc gcc-fortran git tar suitesparse glpk readline --noconfirm
     git clone https://github.com/ferrandi/PandA-bambu.git
     cd PandA-bambu
     make -f Makefile.init
     mkdir build
     cd build && ../configure --prefix=/home/archlinux/panda --enable-verilator --enable-glpk --enable-opt --enable-flopoco --with-opt-level=fast && make -j2 && make install && make clean
     cd ../.. && chown -R archlinux:archlinux PandA-bambu
     mv PandA-bambu /home/archlinux/
     cd /home/archlinux/panda/share/panda/examples/arf && chmod +x bambu.sh && ./bambu.sh && rm -rf arf_hls arf_testbench && echo "Bambu is correctly working!!"
     cd /home/archlinux/ 
     chown -R archlinux:archlinux /home/archlinux/panda
     pacman -Scc --noconfirm
     dd if=/dev/zero of=/EMPTY bs=1M
     rm -f /EMPTY
  SHELL
end
