name: GCC Regression Simple

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Bambu AppImage name"
        required: false
        type: string
        default: bambu-grs
      compilers:
        description: "Front-end compiler string"
        required: false
        type: string
        default: gcc-4.9,clang-4
      configure:
        description: "Bambu build configuration arguments"
        required: false
        type: string
        default: --enable-glpk --enable-flopoco --enable-opt --with-opt-level=2 --enable-release --with-gcc8=/bin/false
      test-compilers:
        description: "Compiler used during tests"
        required: false
        type: string
        default: I386_GCC49
      additional-args:
        description: "Additional arguments to be used during tests"
        required: false
        type: string
        default: ""

jobs:
  build:
    uses: ./.github/workflows/build-appimage.yml
    with:
      version: ${{github.event.inputs.package-name}}
      compilers: ${{ github.event.inputs.compilers }}
      build-compiler: gcc-8
      configure: ${{ github.event.inputs.configure }} CC=gcc-8 CXX=g++-8
    secrets:
      CI_STORAGE_URL: ${{secrets.CI_STORAGE_URL}}
      CI_STORAGE_USER: ${{secrets.CI_STORAGE_USER}}
      CI_STORAGE_TOKEN: ${{secrets.CI_STORAGE_TOKEN}}

  test-suite:
    needs: [build]
    uses: ./.github/workflows/reusable-grs.yml
    with:
      package-name: ${{needs.build.outputs.package-name}}
      test-compilers: ${{github.event.inputs.test-compilers}}
      additional-args: ${{github.event.inputs.additional-args}}
    secrets:
      CI_STORAGE_URL: ${{secrets.CI_STORAGE_URL}}
      CI_STORAGE_USER: ${{secrets.CI_STORAGE_USER}}
      CI_STORAGE_TOKEN: ${{secrets.CI_STORAGE_TOKEN}}
