name: Reusable GCC Regression Simple

on:
  workflow_call:
    inputs:
      package-name:
        description: "Bambu AppImage package name"
        required: true
        type: string
      compiler:
        description: "Compiler used during tests"
        required: true
        type: string
      additional-args:
        description: "Additional arguments to be used during tests"
        required: false
        type: string
        default: ""
    secrets:
      CI_STORAGE_URL:
        required: true
      CI_STORAGE_USER:
        required: true
      CI_STORAGE_TOKEN:
        required: true

env:
  common-args: -c=--simulator=VERILATOR -t150m ${{inputs.additional-args}}

jobs:
  grs:
    uses: ./.github/workflows/reusable-script_call.yml
    with:
      script: generic_gcc_regression_simple_bambu.sh
      package-name: ${{inputs.package-name}}
      compiler: ${{inputs.compiler}}
      args: ${{env.common-args}}
    secrets: inherit
  
  grs-pp:
    needs: [grs]
    uses: ./.github/workflows/reusable-script_call.yml
    with:
      script: generic_gcc_regression_simple_bambu_pretty_print.sh
      package-name: ${{inputs.package-name}}
      compiler: ${{inputs.compiler}}
      args: ${{env.common-args}} --skip_list 20071029-1
    secrets: inherit

  grs-eg:
    needs: [grs]
    uses: ./.github/workflows/reusable-script_call.yml
    with:
      script: generic_gcc_regression_simple_eg_ext_pipelined.sh
      package-name: ${{inputs.package-name}}
      compiler: ${{inputs.compiler}}
      args: ${{env.common-args}}
    secrets: inherit

  grs-eg_ext:
    needs: [grs, grs-eg]
    uses: ./.github/workflows/reusable-script_call.yml
    with:
      script: generic_gcc_regression_simple_eg.sh
      package-name: ${{inputs.package-name}}
      compiler: ${{inputs.compiler}}
      args: ${{env.common-args}}
    secrets: inherit

  libm:
    uses: ./.github/workflows/reusable-script_call.yml
    with:
      script: generic_libm-tests.sh
      package-name: ${{inputs.package-name}}
      compiler: ${{inputs.compiler}}
      args: ${{env.common-args}}
    secrets: inherit
